version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: colserra/ffmpeg:alpha
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/Niffy-the-conqueror/Encode2Tg/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  my-job-name:

    executor: my-custom-executor
    steps:
      - checkout
      - run: 
          name: running test
          command: apt -qq update && apt -qq install -y git wget pv python3-pip jq python3-dev mediainfo && pip3 install -r requirements.txt && bash run.sh
          no_output_timeout: 1.5h
    resource_class: large

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
